version: "3.8"

services:
  temppan:
    build: .
    container_name: jikeqingpan
    restart: unless-stopped
    ports:
      - "8088:8088"
    volumes:
      # 挂载配置文件，方便随时修改 Cookie 等配置
      - ./config.json:/app/config.json:ro
